#!/usr/bin/env python3

import argparse
import json

from collections import deque
from pathlib import Path


def generate_program_data(
    namespace: argparse.Namespace,
    parser: argparse.ArgumentParser,
) -> None:
    source: Path = namespace.version_map
    destination_dir: Path = namespace.package_data_dir

    if not (source.exists() and source.is_file()):
        parser.error(
            f"Version mapping file {source} could not be found or is not a valid file"
        )

    try:
        destination_dir.mkdir(parents=True, exist_ok=True)
        source.copy_into(destination_dir)
    except OSError as e:
        parser.error(f"Failure while copying version map to destination: {e}")


def generate_test_data(
    namespace: argparse.Namespace,
    parser: argparse.ArgumentParser,
) -> None:
    generate_program_data(namespace, parser)

    source: Path = namespace.version_map
    test_data: Path = namespace.test_data_path

    with source.open("r") as sf:
        try:
            version = deque(
                json.load(sf).get("storage", {}).get("values", {}).keys(), maxlen=1
            ).pop()

            with test_data.open("w+") as tf:
                tf.seek(0)
                tf.write(version.lstrip("v"))
                tf.truncate()

        except json.JSONDecodeError as e:
            parser.error(f"Version map file {source} is not valid JSON: {e}")
        except IndexError:
            parser.error("Version map storage values list is empty")


def main() -> None:
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--version-map",
        type=Path,
        default=Path("vendor/duckdb/src/storage/version_map.json"),
        help="Path to version mapping file for DuckDB",
    )
    parser.add_argument(
        "--package-data-dir",
        type=Path,
        default=Path("src/duckdb_upgrade/data"),
        help="Data directory within package",
    )

    subparsers = parser.add_subparsers()
    subparsers.add_parser("gen-program-data").set_defaults(
        func=generate_program_data, parser=parser
    )

    gen_test_data = subparsers.add_parser("gen-test-data")
    gen_test_data.add_argument(
        "--test-data-path",
        type=Path,
        default=Path("tests/latest.txt"),
        help="Generate test data",
    )
    gen_test_data.set_defaults(func=generate_test_data, parser=parser)

    args = parser.parse_args()

    if hasattr(args, "func"):
        args.func(args, args.parser)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
